### PR TITLE
Fix `OutOfMemory` exception in MongoDB 

### LINKED ISSUE #113: Volume API crashes with 500 error
Volume API crashes with 500 error when there is no `&startTime=&endTime=`

```
POST {{baseUrl}}/api/aggregate/BioIT-Demo/{{getDemoSubjectDetail.response.body.$.subjectId}}/distinct
  ?timeWindow=TEN_MIN
Authorization: Bearer {{token.response.body.access_token}}
Content-Type: application/json

{
  "sources":[
     {
        "sourceId":"b6f1a0bb-b663-4aa2-a776-3a51d4dc5f86",
        "sourceData":[
          {"name": "EMPATICA_E4_v1_ACCELEROMETER"}
        ]
     }
  ]
}
```

The front end does not know the effectiveTimeFrame for all `sourcedatatypes`.

### PR DESCRIPTION
**Pull request by nivemaham**
Fix `OutOfMemory` exception in MongoDB by controlling maximum output similar to other APIs

Fixes #113 #107

### CODE REVIEW

File: src/main/java/org/radarcns/webapp/resource/DataSetEndPoint.java [hunk 1]
```diff
@@ -158,20 +166,40 @@ public Dataset getSamplesJson(
...
+        TimeWindow timeWindow = interval;
+        Instant startTime = start.getValue();
+        TimeFrame timeFrame = new TimeFrame(startTime, endTime);
+
+        if (startTime != null && startTime.isAfter(endTime)) {
+            // don't mix up time frame order
+            timeFrame.setStartDateTime(endTime);
+        } else if (startTime == null && timeWindow == null) {
+            // default settings, 1 year with 1 week intervals
+            timeWindow = TEN_SECOND;
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/webapp/resource/DataSetEndPoint.java]: Should be `ONE_WEEK` instead of `TEN_SECOND`. Perhaps fix this at the source as well.

**Review by blootsvoets — COMMENTED** [review]
LGTM. Small fix requested.

File: src/main/java/org/radarcns/webapp/resource/DataSetEndPoint.java [hunk 2]
```diff
@@ -138,7 +142,13 @@ public Dataset getLastReceivedSampleJson(
...
-                    + " Data can be queried using different time-frame resolutions.")
+                    + "Data can be queried using different time-frame resolutions.  If endTime is"
+                    + "not provided the data will be calculated from current timestamp. If the "
+                    + "startTime is not provided startTime will be calculated based on default "
+                    + "number of windows and given timeWindow. If no timeWindow is provided, a "
+                    + "best fitting timeWindow will be calculated. If none of the parameters are "
+                    + "provided, API will return data for a period of a year with ONE_WEEK of t"
+                    + "imeWindow (<54 records) from current timestamp.")
     @ApiResponse(responseCode = "500", description = "An error occurs while executing")
     @ApiResponse(responseCode = "200", description = "Returns a dataset object containing all "
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/webapp/resource/DataSetEndPoint.java]: Add API response 400

File: src/main/java/org/radarcns/webapp/resource/DataSetEndPoint.java [hunk 3]
```diff
@@ -158,20 +168,36 @@ public Dataset getSamplesJson(
...
-                    subjectId, sourceId, sourceDataName, stat, timeWindow,
-                    Date.from(start.getValue()), Date.from(end.getValue()));
-        } else {
-            dataset = dataSetService.getAllDataItems(projectName, subjectId,
-                    sourceId, sourceDataName, stat, timeWindow);
+        // Don't request future data
+        Instant endTime = end != null && end.getValue() != null ? end.getValue() : Instant.now();
+
+        TimeWindow timeWindow = interval;
+        Instant startTime = start != null && start.getValue() != null ? start.getValue() : null;
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/webapp/resource/DataSetEndPoint.java]: Can be simplified to `start != null ? start.getValue() : null`

**Review by blootsvoets — APPROVED** [review]
LGTM. Some optional comments
